name: 'CI/CD'

on:
  # Run on main branch for PR default events + closed event
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]
  # Allow manual build
  workflow_dispatch:

# Only one workflow at a time for a given branch or tag
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci-cd:
    uses: dsb-norge/github-actions/.github/workflows/ci-cd-default.yml@v2
    secrets: inherit # pass all secrets, ok since we trust our own workflow
    with:
      # Github requires inputs of type string, ultimately this will be parsed as yaml array
      apps: |
        - application-name: template-backend    <---- REPLACE THIS!
          application-source-path: .
          pr-deploy-additional-helm-values:
            parameters:
              dsb-spring-boot.database_container.enabled: true
              # Dollar sign and leading curly bracket must be escaped for spring. Ie. '${VAR}' becomes '\$\{VAR}'
              dsb-spring-boot.config.spring.datasource.url: 'jdbc:sqlserver://\$\{DATABASE_CONTAINER_HOST_AND_PORT};database=\$\{DATABASE_CONTAINER_DATABASE};encrypt=false'
              dsb-spring-boot.config.spring.datasource.username: '\$\{DATABASE_CONTAINER_USER}'
              dsb-spring-boot.config.spring.datasource.password: '\$\{DATABASE_CONTAINER_PASSWORD}'
              dsb-spring-boot.config.spring.r2dbc.url: 'r2dbc:pool:sqlserver://\$\{DATABASE_CONTAINER_HOST_AND_PORT}/\$\{DATABASE_CONTAINER_DATABASE}'
              dsb-spring-boot.config.spring.r2dbc.username: '\$\{DATABASE_CONTAINER_USER}'
              dsb-spring-boot.config.spring.r2dbc.password: '\$\{DATABASE_CONTAINER_PASSWORD}'
          maven-build-project-deploy-release-artifacts: true
        - application-name: template-frontend
          application-source-path: ./frontend
          pr-deploy-comment-additional-text: Available at https://pr-${{ github.event.number }}-APPNAME.dev.dsbnorge.no/  <---- REPLACE THIS!
          pr-deploy-additional-helm-values:
            parameters:
              dsb-nginx-frontend.config.LOC_API_PROXY_PASS_HOST: "http://template-backend-pr-${{ github.event.number }}.template-backend-pr-${{ github.event.number }}.svc.cluster.local:8080"<---- REPLACE THIS!
              dsb-nginx-frontend.ingress_host: "pr-${{ github.event.number }}-APPNAME.dev.dsbnorge.no"  <---- REPLACE THIS!
