name: 'CI/CD'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          server-id: github
          cache: maven
          
      - name: Determine version
        run: |
          CURRENT_TIMESTAMP=$(date +'%Y.%m.%d.%s')
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "NEW_VERSION=${CURRENT_TIMESTAMP}-SNAPSHOT" >> $GITHUB_ENV
          else
            echo "NEW_VERSION=${CURRENT_TIMESTAMP}" >> $GITHUB_ENV
          fi
          
      - name: Update Maven version
        run: mvn --quiet versions:set -DnewVersion="${{ env.NEW_VERSION }}"
        
      - name: Build and verify
        run: mvn --quiet clean verify
        
      - name: Deploy to GitHub Packages
        # Only deploy on pushes to main (not on PRs)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: mvn --quiet --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}