name: 'CI/CD'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Determine version
        run: |
          CURRENT_TIMESTAMP=$(date +'%Y.%m.%d.%s')
          if [ "${{ github.event_name }}" = "pull_request" ] && [ "${{ github.event.pull_request.head.repo.full_name }}" = "${{ github.repository }}" ]; then
            echo "NEW_VERSION=${CURRENT_TIMESTAMP}-SNAPSHOT" >> $GITHUB_ENV
          else
            echo "NEW_VERSION=${CURRENT_TIMESTAMP}" >> $GITHUB_ENV
      - name: Update Maven version
        run: mvn versions:set -DnewVersion="${{ env.NEW_VERSION }}"
      - name: Build with Maven
        run: mvn clean package
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: keycloak-friendly-captcha-jar
          path: target/keycloak-friendly-captcha-1.0-SNAPSHOT.jar